name: Deploy Flutter Web

on:
  push:
    branches:
      - main   # Deploy on every push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter 3.16.5
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.16.5'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web (release)
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          
